apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-hello-docker-tested
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-hello-docker-tested
    app.kubernetes.io/part-of: java-quarkus-hello-docker-tested
  name: java-quarkus-hello-dockeroggk
spec:
  path: /
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: java-quarkus-hello-docker-tested
    weight: null
status: {}
